---
- name: Первоначальная настройка серверов
  hosts: servers
  become_method: sudo
  become_user: root

  tasks:
  - name: Обновить все пакеты
    dnf:
      name: '*'
      state: latest

  - name: Установить группу программ
    dnf:
      name: 
        - mc
        - net-tools
        - network-scripts
        - wget
        - tar
        - git
        - bash-completion
        - nfs-utils
        - rsyslog
        - python3
      state: latest

  - name: Отключаем SELinux
    selinux:
      state: disabled

  - name: Отключаем firewalld
    ansible.builtin.service:
      name: firewalld
      enabled: no

  - name: Отключаем NetworkManager
    ansible.builtin.service:
      name: NetworkManager
      enabled: no

  - name: Включаем Network-Scripts
    ansible.builtin.service:
      name: network
      enabled: yes


  - name: Отключаем на всех узлах SWAP
    shell:
      cmd: |
        swapoff -a
    args:
      executable: /bin/bash

  - name: Комментируем в fstab
    replace:
      path: /etc/fstab
      regexp: '(.*swap.*)'
      replace: '#\1' 
 

  - name: Копируем UUID в файл
    shell:
      cmd: |
        grep UUID /etc/sysconfig/network-scripts/ifcfg-ens18 > /etc/sysconfig/network-scripts/ifcfg-vrem
    args:
      executable: /bin/bash


  - name: Настраиваем сетевой адаптер
    template:
      src: files/network.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-ens18

  - name: Восстонавливаем UUID в файл
    shell:
      cmd: |
        cat /etc/sysconfig/network-scripts/ifcfg-vrem >> /etc/sysconfig/network-scripts/ifcfg-ens18
        rm -f /etc/sysconfig/network-scripts/ifcfg-vrem
    args:
      executable: /bin/bash


  - name: Настраиваем HostName
    template:
      src: files/hostname.j2
      dest: /etc/hostname






  - name: Перезагрузка хостов и ожидание их перезагрузки
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami


